apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hello-world-dev
  namespace: argocd
spec:
  destination:
    namespace: argocd
    name: in-cluster
  project: default
  sources:
    - repoURL: https://github.com/AdarshGE/ArgoCD.git
      path: CDCnew
      targetRevision: HEAD
        valueFiles:
        - $values/deployment/values-dev.yaml
    # Values from Git
    - repoURL: 'https://github.com/AdarshGE/ArgoCD.git'
      targetRevision: HEAD
      ref: values
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
