apiVersion: v1
kind: ConfigMap
metadata:
  name: my-configmap1
data:
{{- range $databasedetails := .Values.database }}
{{- $siteName := $databasedetails.siteID }}
{{- range $siteDetails := $databasedetails.SiteDetails }}
  {{- range $key, $value := $databasedetails.SiteDetails }}
  {{$key}}_{{$siteName}}: {{ quote $value.password }}
  
  {{- end }}
{{- end }}
{{- end }}

